### ISSUE TITLE
Tuple unpacking examples given in readme.md do not compile.

### ISSUE THREAD

**Issue by NTDLS** [iAJTin/iCPUID#2]
**Code (.net 8.0):**
```
CPUID cpuid = CPUID.Instance;
ReadOnlyCollection<Leaf> leafs = cpuid.ImplementedLeafs;
foreach (var (leaf, subLeafs) in leafs)
{
}
```

**Compile Errors:**
- 'Leaf' does not contain a definition for 'Deconstruct' and no accessible extension method 'Deconstruct' accepting a first argument of type 'Leaf' could be found.
- No suitable 'Deconstruct' instance or extension method was found for type 'Leaf', with 2 out parameters and a void return type.
- Cannot infer the type of implicitly-typed deconstruction variable 'leaf'.
- Cannot infer the type of implicitly-typed deconstruction variable 'subLeafs'.

**Comment by iAJTin** [comment]
Hello,
I have tried the net 8 version and I have not had any problems.

Just remember, to use deconstructors you need at least version 7 c#, on the other hand the version of net8 on my machine is 8.0.400 (I don't think this is relevant but so you have more information)

Comment anything!

**Comment by NTDLS** [comment]
Thanks for looking into it, I know digging out a project can be a hassle - so I appreciate it! 👍 

I've tried this on two installations using C# 8 in Visual Studio 2022, am I using the wrong nuget package?
`<PackageReference Include="iCPUID" Version="1.0.6" />`

![image](https://github.com/user-attachments/assets/22e5b98b-5e88-4dfe-8a31-63c10707c8a9)
![image](https://github.com/user-attachments/assets/15ff4cde-5e9e-44da-847a-1da8254f1c24)

**Comment by iAJTin** [comment]
Hello,

I have already detected the problem, 

The documentation was not even updated.

I shouldn't have updated at the time and I hadn't realized.

If you try again now everything should work as expected.

And sorry for the mistake.

All the best!

**Comment by NTDLS** [comment]
Fantastic, this is working perfectly! Thanks for the assist!!!
